### ISSUE TITLE
[Bug] torch dynamo cannot find hidet backend

### ISSUE THREAD

**Issue by GisellWu** [hidet-org/hidet#166]
**Describe the bug**
I'm trying to optimize pytorch models with hidet. However, whether installing hidet via pip or from source, it will produce an error that the backend cannot be found:

File "cell1.py", line 12, in <module>
    model_opt = torch.compile(model, backend='hidet')
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 1419, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 426, in optimize
    backend = get_compiler_fn(backend)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 356, in get_compiler_fn
    compiler_fn = lookup_backend(compiler_fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 365, in lookup_backend
    compiler_fn = BACKENDS[compiler_fn]
KeyError: 'hidet'

**To Reproduce**
gallery/getting-started/quick-start.py

**Expected behavior**
Theoretically, torch dynamo should have registered the hidet backend after successful installation. Do you have any idea about it?

**Enviroment**
 - Python verison: 3.8.10
 - Hidet version: 0.2.2.dev
 - PyTorch version: 2.0.0+cu116
 - OS: Ubuntu 22.04.2 LTS
 - GPU: NVIDIA A10
 - GPU driver: 525.85.12

**Comment by yaoyaoding** [comment]
Hi Ruofan,

Seems like your torch package is an old-version one. The official pytorch 2.0 seems only have cuda 11.7 and cuda 11.8. Could you try to reinstall the pytorch package? (say, `pip3 install --upgrade torch torchvision torchaudio` would install the one with cuda 11.7).

**Comment by GisellWu** [comment]
> Hi Ruofan,
> 
> Seems like your torch package is an old-version one. The official pytorch 2.0 seems only have cuda 11.7 and cuda 11.8. Could you try to reinstall the pytorch package? (say, `pip3 install --upgrade torch torchvision torchaudio` would install the one with cuda 11.7).

Hi Yaoyao,

Thanks for the suggestion, torch 2.1.0+cu118 is ok. However, an error is still reported when running the model. Do you have any idea about it?

Compiling cuda task adds(x=float32[1, 64, 1, 1])...
Compiling cuda task rsqrt(x=float32[1, 64, 1, 1])...
Compiling cuda task adds(x=float32[1, 128, 1, 1])...
Compiling cuda task rsqrt(x=float32[1, 128, 1, 1])...
Compiling cuda task adds(x=float32[1, 256, 1, 1])...
Compiling cuda task rsqrt(x=float32[1, 256, 1, 1])...
Compiling cuda task adds(x=float32[1, 512, 1, 1])...
Compiling cuda task rsqrt(x=float32[1, 512, 1, 1])...
Compiling cuda task rearrange(x=float32[1000, 512])...
Compiling cuda task negative(x=float32[1, 64, 1, 1])...
Compiling cuda task negative(x=float32[1, 128, 1, 1])...
Compiling cuda task negative(x=float32[1, 256, 1, 1])...
Compiling cuda task negative(x=float32[1, 512, 1, 1])...
Compiling cuda task mul(x=float32[1, 64, 1, 1], y=float32[1, 64, 1, 1])...
Compiling cuda task add(x=float32[1, 64, 1, 1], y=float32[1, 64, 1, 1])...
Compiling cuda task mul(x=float32[1, 128, 1, 1], y=float32[1, 128, 1, 1])...
Compiling cuda task add(x=float32[1, 128, 1, 1], y=float32[1, 128, 1, 1])...
Compiling cuda task mul(x=float32[1, 256, 1, 1], y=float32[1, 256, 1, 1])...
Compiling cuda task add(x=float32[1, 256, 1, 1], y=float32[1, 256, 1, 1])...
Compiling cuda task mul(x=float32[1, 512, 1, 1], y=float32[1, 512, 1, 1])...
Compiling cuda task add(x=float32[1, 512, 1, 1], y=float32[1, 512, 1, 1])...
Compiling cuda task mul(x=float32[64, 3, 7, 7], y=float32[64, 1, 1, 1])...
Compiling cuda task mul(x=float32[64, 64, 3, 3], y=float32[64, 1, 1, 1])...
Compiling cuda task mul(x=float32[128, 64, 3, 3], y=float32[128, 1, 1, 1])...
Compiling cuda task mul(x=float32[128, 128, 3, 3], y=float32[128, 1, 1, 1])...
Compiling cuda task mul(x=float32[128, 64, 1, 1], y=float32[128, 1, 1, 1])...
Compiling cuda task mul(x=float32[256, 128, 3, 3], y=float32[256, 1, 1, 1])...
Compiling cuda task mul(x=float32[256, 256, 3, 3], y=float32[256, 1, 1, 1])...
Compiling cuda task mul(x=float32[256, 128, 1, 1], y=float32[256, 1, 1, 1])...
Compiling cuda task mul(x=float32[512, 256, 3, 3], y=float32[512, 1, 1, 1])...
Compiling cuda task mul(x=float32[512, 512, 3, 3], y=float32[512, 1, 1, 1])...
Compiling cuda task mul(x=float32[512, 256, 1, 1], y=float32[512, 1, 1, 1])...
Compiling cuda task broadcast(data=float32[512, 1000])...
Compiling cuda task rearrange(x=float32[1, 8, 64, 1000])...
Compiling cuda task rearrange(x=float32[1, 64, 3, 7, 7])...
Compiling cuda task rearrange(x=float32[1, 64, 64, 3, 3])...
Compiling cuda task rearrange(x=float32[1, 128, 64, 3, 3])...
Compiling cuda task rearrange(x=float32[1, 128, 128, 3, 3])...
Compiling cuda task rearrange(x=float32[1, 128, 64, 1, 1])...
Compiling cuda task rearrange(x=float32[1, 256, 128, 3, 3])...
Compiling cuda task rearrange(x=float32[1, 256, 256, 3, 3])...
Compiling cuda task rearrange(x=float32[1, 256, 128, 1, 1])...
Compiling cuda task rearrange(x=float32[1, 512, 256, 3, 3])...
Compiling cuda task rearrange(x=float32[1, 512, 512, 3, 3])...
Compiling cuda task rearrange(x=float32[1, 512, 256, 1, 1])...
Compiling cuda task rearrange(x=float32[1, 4, 144, 64])...
Compiling cuda task rearrange(x=float32[1, 8, 72, 128])...
Compiling cuda task rearrange(x=float32[1, 8, 144, 128])...
Compiling cuda task rearrange(x=float32[1, 8, 8, 128])...
Compiling cuda task rearrange(x=float32[1, 8, 144, 256])...
Compiling cuda task rearrange(x=float32[1, 8, 288, 256])...
Compiling cuda task rearrange(x=float32[1, 8, 16, 256])...
Compiling cuda task rearrange(x=float32[1, 8, 288, 512])...
Compiling cuda task rearrange(x=float32[1, 8, 576, 512])...
Compiling cuda task rearrange(x=float32[1, 8, 32, 512])...
Traceback (most recent call last):
  File "cell1.py", line 15, in <module>
    y1 = model_opt(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 111, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 247, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 394, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 446, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 113, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 293, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 358, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 683, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 345, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1890, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 609, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 569, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1977, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 624, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 694, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 776, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 772, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 1093, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/frontend/torch/dynamo_backends.py", line 144, in hidet_backend
    executor = generate_executor(flow_graph)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/frontend/torch/dynamo_backends.py", line 68, in generate_executor
    cuda_graph: CudaGraph = graph_opt.cuda_graph()
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/ir/flow_graph.py", line 348, in cuda_graph
    return CudaGraph(self)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/cuda/graph.py", line 117, in __init__
    inputs.append(randn_like(tensor, device='cuda'))
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/tensor.py", line 1307, in randn_like
    return randn(
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/tensor.py", line 1104, in randn
    hidet_tensor = from_numpy(np_tensor)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/tensor.py", line 1336, in from_numpy
    return from_dlpack(nparray)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/tensor.py", line 1356, in from_dlpack
    raise RuntimeError('Expect a dltensor that implements __dlpack__ method.')
torch._dynamo.exc.BackendCompilerFailed: backend='hidet_backend' raised:
RuntimeError: Expect a dltensor that implements __dlpack__ method.


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

**Comment by yaoyaoding** [comment]
Hi @GisellWu,

Can I know your numpy version? Hidet replies on the DLPack protocol to exchange tensor with numpy, and this protocol is only supported since numpy 1.13. 

See also: 
- https://dmlc.github.io/dlpack/latest/index.html
- numpy.from_dlpack: https://numpy.org/doc/1.23/reference/generated/numpy.from_dlpack.html

**Comment by GisellWu** [comment]
> Hi @GisellWu,
> 
> Can I know your numpy version? Hidet replies on the DLPack protocol to exchange tensor with numpy, and this protocol is only supported since numpy 1.23.
> 
> See also:
> 
> * https://dmlc.github.io/dlpack/latest/index.html
> * numpy.from_dlpack: https://numpy.org/doc/1.23/reference/generated/numpy.from_dlpack.html

Hi yaoyao,

Thanks for your help! I successfully run the model after I upgrade numpy to 1.23.
