### ISSUE TITLE
[Bug] softmax() got an unexpected keyword argument '_stacklevel'

### ISSUE THREAD

**Issue by GisellWu** [hidet-org/hidet#177]
**Describe the bug**
I try to optimize the HuggingFace Bert model with hidet in Pytorch. It reports the following error:

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias']
This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Compiling cuda task full(shape=[], value=-10000.0, dtype=float32)...
Compiling cuda task slice(data=int64[1, 512])...
Compiling cuda task take(data=float32[512, 768], indices=int64[1, 12])...
Compiling cuda task rearrange(x=float32[768, 768])...
Compiling cuda task full(shape=[], value=8.0, dtype=float32)...
Traceback (most recent call last):
  File "bert_test.py", line 29, in <module>
    output = model_opt(**encoded_input)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 111, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 247, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 394, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 446, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 113, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 293, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 358, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 683, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 345, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1890, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 609, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 569, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1977, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 648, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 694, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 776, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 772, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 1093, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/frontend/torch/dynamo_backends.py", line 140, in hidet_backend
    output = interpreter(*symbolic_inputs)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/frontend/torch/interpreter.py", line 152, in __call__
    return self.forward(*args)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/frontend/torch/interpreter.py", line 262, in forward
    self._raise_exception(e, hidet_func, hidet_args, hidet_kwargs)
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/frontend/torch/interpreter.py", line 218, in _raise_exception
    raise type(exception)(
torch._dynamo.exc.BackendCompilerFailed: backend='hidet_backend' raised:
TypeError: softmax() got an unexpected keyword argument '_stacklevel', occurred when calling softmax with 
    args: (<hidet.Tensor object at 0x7f4a9850d370>, -1)
  kwargs: {'_stacklevel': 5}
softmax is defined at
  File "/home/wuruofan/workspace/hidet-main/python/hidet/graph/frontend/torch/register_functions.py", line 208

You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

**To Reproduce**
from transformers import BertTokenizer, BertModel, BertConfig
import torch

config = BertConfig(num_hidden_layers=2)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased").to(device="cuda:0")

model_opt = torch.compile(model, backend='hidet')

text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt').to(device="cuda:0")
output = model_opt(**encoded_input)

**Expected behavior**
It seems that there is some problem with softmax op, do you have a good solution for it? Or is there any other way I can run the Bert model with torch dynamo?

**Enviroment**
 - Python verison: 3.8.10
 - Hidet version: 0.2.2.dev
 - PyTorch version: 2.1.0+cu118
 - Numpy version: 1.23
 - OS: Ubuntu 22.04.2 LTS
 - GPU: NVIDIA A10
 - GPU driver: 525.85.12

**Comment by yaoyaoding** [comment]
Hi @GisellWu,

I am trying to fix this bug in #178. However, I can not reproduce the error on my side (with the latest main branch of hidet and torch 2.1.0.dev20230417+cu118). You can try installing hidet from source after I merge #178 to see whether the error exists.

**Comment by yaoyaoding** [comment]
Feel free to reopen this issue if it has not been addressed.
